### PR TITLE
Support for node-inspector v3.2.

### PR DESCRIPTION
**Pull request by neilgoodman**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This should also include a version update to the node-inspector dependency in package.json, right?

**Comment by neilgoodman** [comment]
package.json lists the version for node-inspector as 0 and when I run `npm install` this just gets the latest version. This was the reason I made this change, because I ran `npm update -g` this morning and node-debug broke on me.

I think it would be a nice change if versions of the dependencies were given in the package.json so these breaks don't happen in the future.

**Comment by popomore** [comment]
Will this pr be merged?

**Comment by jfirebaugh** [comment]
Superceded by #3.

**Pull request closed without merging**
